### ISSUE TITLE
Compiler internal error: com.google.common.css.compiler.ast.CssMixinNode cannot be cast to com.google.common.css.compiler.ast.CssDeclarationNode

### ISSUE THREAD

**Issue by xasima** [DisDis/ClosurePlatform#2]
Не могу запустить  пример с использованием GSS миксинов. 

1) Файл 3-typography.gss определяет миксин 

```
@defmixin large() {
  font-size: 2em; /* 30px */
  line-height: 1.4667em; /* 44px */
  margin-top: 0.7333em;
  margin-bottom: 0em;
}

.large {
  @mixin large();
}
```

Файл 5-main.gss пытается использовать этот миксин

```
h1 {
    @mixin large();
}
```

Полный пример см. https://gist.github.com/xasima/5338461 

При вызове серии cd tools && ./clean.sh && ./compile.templates.sh генерируется ошибка. При этом порядок обработки GSS файлов (судя по логу Scan)  - правилен. 

```
------== Scan GSS files ==------
   found './../themes/default/gss/2-typography.gss'
   found './../themes/default/gss/0-definitions.gss'
   found './../themes/default/gss/5-main.gss'
------== GSS ==------
------== SOY ==------
   Compiling SOY....Compiler internal error: com.google.common.css.compiler.ast.CssMixinNode cannot be cast to com.google.common.css.compiler.ast.CssDeclarationNode
java.lang.ClassCastException: com.google.common.css.compiler.ast.CssMixinNode cannot be cast to com.google.common.css.compiler.ast.CssDeclarationNode
        at com.google.common.css.compiler.passes.DisallowDuplicateDeclarations.enterRuleset(DisallowDuplicateDeclarations.java:64)
        at com.google.common.css.compiler.ast.DefaultVisitController$VisitRulesetState.doVisit(DefaultVisitController.java:762)
        at com.google.common.css.compiler.ast.DefaultVisitController.startVisit(DefaultVisitController.java:1762)
        at com.google.common.css.compiler.passes.DisallowDuplicateDeclarations.runPass(DisallowDuplicateDeclarations.java:75)
        at com.google.common.css.compiler.passes.PassRunner.runPasses(PassRunner.java:142)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.java:106)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:94)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:129)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:293)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:366)
.ERROR
OK
```

**Comment by DisDis** [comment]
Для этого мы все миксыны вынесли в 0-definitions.gss
Потому как 0-definitions.gss подключается при компиляции любого gss файлы, это был единственный путь избежать выше изложенных проблем.

**Comment by DisDis** [comment]
Вот допустим у нас объявлен в 0-definitions.gss

```
@defmixin gradient(FALLBACK_COLOR, COLOR_TOP, COLOR_TOP_POS, COLOR_MIDDLE, COLOR_MIDDLE_POS, COLOR_BOTTOM, COLOR_BOTTOM_POS) {
 background: FALLBACK_COLOR; /* fallback color if gradients are not supported */ 
    /* @alternate */ background: -moz-linear-gradient(top, COLOR_TOP COLOR_TOP_POS, COLOR_MIDDLE COLOR_MIDDLE_POS, COLOR_BOTTOM COLOR_BOTTOM_POS); /* FF3.6+ */
    /* @alternate */ background: -webkit-gradient(linear, left top, left bottom, color-stop(COLOR_TOP_POS, COLOR_TOP), color-stop(COLOR_MIDDLE_POS, COLOR_MIDDLE), color-stop(COLOR_BOTTOM_POS, COLOR_BOTTOM)); /* Chrome,Safari4+ */
    /* @alternate */ background: -webkit-linear-gradient(top, COLOR_TOP COLOR_TOP_POS, COLOR_MIDDLE COLOR_MIDDLE_POS, COLOR_BOTTOM COLOR_BOTTOM_POS); /* Chrome10+, Safari5.1+ */
    /* @alternate */ background: linear-gradient(top, COLOR_TOP COLOR_TOP_POS, COLOR_MIDDLE COLOR_MIDDLE_POS, COLOR_BOTTOM COLOR_BOTTOM_POS); /* W3C */
}
```

А используем его в любом gss файле так

```
.aaaa{
        width:235px;
        height: 146px;
        padding: 3px;
        margin:0 4px 8px;
        color: white;
        text-align: right;
        @mixin borderRadius(6px);
        @mixin gradient(#005B8F, #005B8F, 0%, #004C7D, 50%, #003D6B, 100%);
    }
```

**Comment by xasima** [comment]
Да, видно, что 0-definitions.gss содержит некоторые общеупотребляемые миксины. Единственное, было не сразу понятно, что это единственное место, где у вас миксины можно объявлять. Возможно, это надо явно описать в документации, когда она здесь появится. 

Возможное решение ситуации
1) в конфигурационном файле /  коде,  на риск пользователя,  явно задать список gss- файлов, содержащих миксины и обрабатывающихся в заданном порядке.
2) создать скрипт, который берет конфигурационный файл с определенным в нем порядком gss базовых (миксинных) файлов и склеивает их в definition.gss. Последний (на втором этапе) уже обрабатывается стандартным проходом. 
3) генерировать конфигурационный файл из п.1. на основании @require и @provide из #1

**Comment by DisDis** [comment]
Я сегодня постараюсь обновить код проекта, так как мы добавили возможность сборки gss в таком виде:
И так в режиме отладки она создаёт css файлы и структуру каталогов аналогичную gss то есть если у нас в теме есть такая структура:

```
gss/
     0-reset.gss
     1-1fonts.gss
     ...какие-то файлы...
     full/ (папка)
          2-modal.gss
          ...какие-то файлы...
```

То на выходе будет 

```
css/
     0-reset.css
     1-1fonts.css
     ...какие-то файлы..
     full/ (папка)
          2-modal.css
          ...какие-то файлы...
```

В режиме релиза работает всё иначе, там все gss файлы которые были в корне gss папки пакуются в theme.css, а все каталоги превращаются в одноимённые <название папки>.css

И так если верхний вариант примера пропустить через релизную сборку то на выходе будет:

```
css/
     theme.css
     full/full.css
```

При этом при сборке всех внутренних папок подключается файл 0-definitions.gss из корня папки gss, для того что бы дефиниции можно было использовать в любом сжимаемом файле.

Структуру каталогов нельзя делать глубокую, допустим 1 уровень вложения.

**Comment by hochhaus** [comment]
I think this is caused by https://github.com/google/closure-stylesheets/issues/70.
