### ISSUE TITLE
Можно ли осуществить компиляции SOY файлов в нескольких папках

### ISSUE THREAD

**Issue by xasima** [DisDis/ClosurePlatform#6]
build.soy.properties содержит единственную папку, в которой предполагается поиск soy для  их последующей компиляции

```
soy.tools.dir=./tools
soy.theme.dir=./themes
```

Желательно  иметь возможность указывать несколько папок для поиска и компиляции soy файлов. 

```
soy.tools.dir=./tools
soy.theme.dir=./themes
soy.soy.dir=./WebUI/js/other_not_dependent-on-theme_framework_that_contains_soy
```

Например, relief фреймворк, написанный на Google Closure, содержит внутри себя нескомпилированный soy файл. В настоящий момент приходиться отдельно компилировать такие soy файлы.

**Comment by xasima** [comment]
Вероятно, для решения этой ситуации нужно будет произвести автоматическую компиляция soy в других папках (в заданных папках) лишь один раз. Т.е. сценарий: 
1) создание инструкции `soy.other_soy.dir=./WebUI/js/other_framework_with_soy`, 
2) получение js файлов из soy, 
3) комментирование soy.other_soy.dir для того, чтобы избежать возможного дублирования provide инструкций (c soy и скомпилированного js) при последующих запусках. 

Cм. похожее описание для, например, relief и Plovr
Since Plovr compiles Soy templates along with the rest of the app, the compiled template files cannot be included with Relief because doing so would raise a duplicate provide when running Plovr. The workaround for this is that, if you are not using Plovr, to compile the /relief/relief/handlers/handlers.soy template file yourself and re-generate the deps file.

**Comment by DisDis** [comment]
а чем не устраивает поместить soy файлы в отдельную папку в теме?
Просто темы были созданы изначально для того что бы можно было менять внешний вид приложения без изменения логики + локализация.

**Comment by xasima** [comment]
Согласен, думаю можно ограничиться предупреждением в документации.
